import {
  Activity,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AudioLines,
  BookOpen,
  Bookmark,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  CircleHelp,
  Circle,
  Clock3,
  Compass,
  Copy,
  Download,
  Eye,
  FileText,
  Fingerprint,
  Folder,
  Grid2X2,
  Headphones,
  KeyRound,
  Lightbulb,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  Menu,
  Moon,
  MoreHorizontal,
  Orbit,
  Pause,
  Play,
  Plus,
  Radio,
  RotateCcw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  SquareTerminal,
  Square,
  Star,
  Sun,
  Trash2,
  Triangle,
  Upload,
  Volume2,
  VolumeX,
  Waves,
  X,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  audio: AudioLines,
  book: BookOpen,
  bookmark: Bookmark,
  check: Check,
  checks: CheckCheck,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  fast: ChevronsRight,
  help: CircleHelp,
  circle: Circle,
  clock: Clock3,
  compass: Compass,
  copy: Copy,
  download: Download,
  eye: Eye,
  file: FileText,
  fingerprint: Fingerprint,
  folder: Folder,
  grid: Grid2X2,
  headphones: Headphones,
  key: KeyRound,
  lightbulb: Lightbulb,
  lock: LockKeyhole,
  mail: Mail,
  map: Map,
  pin: MapPin,
  menu: Menu,
  moon: Moon,
  more: MoreHorizontal,
  orbit: Orbit,
  pause: Pause,
  play: Play,
  plus: Plus,
  radio: Radio,
  reset: RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: SquareTerminal,
  square: Square,
  star: Star,
  sun: Sun,
  trash: Trash2,
  triangle: Triangle,
  upload: Upload,
  volume: Volume2,
  muted: VolumeX,
  waves: Waves,
  x: X,
  zap: Zap,
}
export function Icon({
  name,
  size = 20,
  className = '',
  strokeWidth = 1.7,
}: {
  name: string
  size?: number
  className?: string
  strokeWidth?: number
}) {
  const Component = icons[name] ?? FileText
  return (
    <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />
  )
}
